# Generated by Django 2.2.5 on 2019-10-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191001_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='anonymous', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
