# Generated by Django 2.2.5 on 2019-09-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=50)),
                ('player2', models.CharField(max_length=50)),
                ('row', models.IntegerField(default=3)),
                ('col', models.IntegerField(default=3)),
                ('ended', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(check=models.Q(ended__lte=5), name='ended_lte_5'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(check=models.Q(row__gte=1), name='row_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(check=models.Q(col__gte=1), name='col_gte_1'),
        ),
    ]
