# Generated by Django 2.2.5 on 2019-09-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.CharField(default='anonymous', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.CharField(default='computer', max_length=50),
        ),
    ]
